 <h1 style="color:blue">Mean Normalization</h1>
 <p>In Machine Learning we use to train a large number of data is required to Trained.For this purpose the machine learning algorithm need to be a  <b>Normalized data</b> for doing work or result correctly it is also called <b>feature scaling</b></p>
    <h2 style="color:red">Why do we do Mean Normalization?</h2>
    <p>it is used to ensure that all data are in similar scale which means that all data are in similar range of data For example we have a dataset of range 0 to 5000 which we normalized between 0 to 1</p>
 

Firstly,We will create a numpy array between 0 to 5000

In [1]:
import numpy as np
X= np.random.randint(0,5001,size=(1000,20)) #create numpy array

In [2]:
print(X)
print(X.shape) #shape of the array

[[2340 2139 1273 ...    1 3018 4577]
 [ 783 3085 3286 ...  301 4578 2606]
 [4248  789 4991 ...  874 3470 1331]
 ...
 [4303 1985 4735 ... 4441  917 4860]
 [4494  339 3176 ...  752 4560 2280]
 [  43 1011  250 ... 4355  766 4008]]
(1000, 20)


Finding the mean of columns and standard deviation

In [3]:
ave_cols =np.mean(X,axis=0)
std_cols = np.std(X,axis=0)

In [4]:
print(ave_cols) #print the means colums
print(std_cols) #print the standard deviation colums
print(ave_cols.shape) 
print(std_cols.shape)

[2433.346 2506.311 2501.829 2481.138 2474.177 2546.924 2507.64  2566.137
 2522.041 2535.311 2482.447 2528.132 2492.034 2530.959 2529.598 2472.932
 2497.201 2493.291 2472.629 2552.259]
[1428.89262028 1451.14795327 1446.93955498 1459.49837443 1457.34867471
 1445.49103914 1433.68357471 1443.30307705 1414.4772205  1430.8874506
 1453.81471969 1421.1165     1419.07233461 1454.61800117 1451.31745059
 1460.9686935  1473.57600096 1424.93262448 1458.87036277 1469.86212888]
(20,)
(20,)


Now we find mean Normalization through X_norm=(X-mean)/std

In [6]:
X_norm=(X-ave_cols)/std_cols

In [7]:
print(X_norm)
print(X_norm.shape)

[[-0.06532751 -0.25311754 -0.84926077 ... -1.74905884  0.37383102
   1.37750403]
 [-1.15498252  0.39878015  0.54195146 ... -1.53852257  1.44315153
   0.03656193]
 [ 1.26997227 -1.18341551  1.72030061 ... -1.13639829  0.68365979
  -0.83086636]
 ...
 [ 1.30846361 -0.35924042  1.54337546 ...  1.36687796 -1.06632436
   1.57003909]
 [ 1.44213356 -1.49351484  0.46592893 ... -1.22201637  1.43081322
  -0.18522758]
 [-1.67286608 -1.03043318 -1.55627026 ...  1.30652423 -1.1698291
   0.99039289]]
(1000, 20)


<h1>Data Sepration</h1>
<ul>
    <li>Training Set</li>
    <li>A Cross Validation Set</li>
    <li>A Test Set</li>
</ul>
<p>The dataset is usually divided such that 60% training set 20% cross validation set and 20% test set</p>

In [8]:
row,column=X_norm.shape
row_indices = np.random.permutation(row)


In [10]:
print(row_indices.shape)

(1000,)


In [11]:
X_train = X_norm[row_indices[0:600]]
X_cross_val = X_norm[row_indices[600:800]]
X_test = X_norm[row_indices[800:1000]]

In [12]:
print("X_training Set:\n ",X_train)
print("X_Cross_Validation Set:\n ",X_cross_val)
print("X_Test set:\n ",X_test)


X_training Set:
  [[ 1.74866464 -0.69208036 -0.82438067 ... -0.80445277  1.56790559
   0.5889947 ]
 [ 1.06141916  0.22374631  1.03471565 ... -0.20793334  0.34572709
   1.37002033]
 [ 0.16632041  1.22157703  1.26831214 ...  1.74443967 -1.61263746
  -0.24577747]
 ...
 [-0.60980509  0.97349757 -1.59773709 ...  1.4040727  -1.62497578
  -0.01786494]
 [ 0.95854229 -0.6445318   1.71546281 ... -1.4522027  -0.98749624
   1.2217071 ]
 [-1.1430852   1.50204464  1.08931364 ... -1.43465801  0.32242138
   0.06445571]]
X_Cross_Validation Set:
  [[ 1.0194286   0.46080002 -0.64538218 ...  0.7493049   0.4245552
   0.58287167]
 [-0.81765836  0.09832836 -1.09253285 ...  0.22787674  0.59454974
   0.76452136]
 [ 1.47292664 -0.25105021 -0.64538218 ...  1.20195788 -0.58170282
   0.43796012]
 ...
 [-0.5573169   1.50893573 -0.18233588 ...  0.32191627  1.26493145
   0.88970317]
 [-0.51462649  0.40498214  0.57581604 ... -0.41706604 -0.0230514
  -0.81249729]
 [-1.64977128 -0.51360097  1.4258861  ... -1.01919977 -0